# Project Name
TARGET = DualUartMidiRx

APP_TYPE = BOOT_SRAM
LDSCRIPT = alt_sram.lds

# Sources
CPP_SOURCES = DualUartMidiRx.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
